plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kapt)
    alias(libs.plugins.hilt)
}

android {
    namespace 'com.lmw.watermonitorandroid.domain.system.impl'
    compileSdk 35

    defaultConfig {
        minSdk 24
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation project(':domain:system:api')
    implementation project(':platform:network')
    implementation project(':platform:util')

    implementation libs.retrofit
    implementation libs.retrofit.converter.gson

    implementation libs.hilt.android
    kapt libs.hilt.compiler

    implementation libs.kotlinx.coroutines.core
}